/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface CCard {
    'theme': string;
  }
  interface CCardAttributes extends StencilHTMLAttributes {
    'theme'?: string;
  }

  interface CCodeSample {
    'type': string;
  }
  interface CCodeSampleAttributes extends StencilHTMLAttributes {
    'type'?: string;
  }

  interface CColumn {
    'lg': any;
    'md': any;
    'sm': any;
    'xl': any;
  }
  interface CColumnAttributes extends StencilHTMLAttributes {
    'lg'?: any;
    'md'?: any;
    'sm'?: any;
    'xl'?: any;
  }

  interface CContainer {
    'type'?: '' | 'fluid' | 'flex';
  }
  interface CContainerAttributes extends StencilHTMLAttributes {
    'type'?: '' | 'fluid' | 'flex';
  }

  interface CContent {
    'router': Boolean;
    'theme': string;
  }
  interface CContentAttributes extends StencilHTMLAttributes {
    'router'?: Boolean;
    'theme'?: string;
  }

  interface CField {
    'type': string;
    'value': string;
  }
  interface CFieldAttributes extends StencilHTMLAttributes {
    'type'?: string;
    'value'?: string;
  }

  interface CFooter {
    'items': any;
    'theme': string;
  }
  interface CFooterAttributes extends StencilHTMLAttributes {
    'items'?: any;
    'theme'?: string;
  }

  interface CHeader {
    'items': any;
    'primaryItems': any;
    'secondaryItems': any;
    'siteName': string;
    'siteUrl': string;
    'theme': string;
  }
  interface CHeaderAttributes extends StencilHTMLAttributes {
    'items'?: any;
    'primaryItems'?: any;
    'secondaryItems'?: any;
    'siteName'?: string;
    'siteUrl'?: string;
    'theme'?: string;
  }

  interface CHelloWorld {
    'text': String;
  }
  interface CHelloWorldAttributes extends StencilHTMLAttributes {
    'text'?: String;
  }

  interface CIcon {
    'name': string;
  }
  interface CIconAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface CList {
    'items': any;
  }
  interface CListAttributes extends StencilHTMLAttributes {
    'items'?: any;
  }

  interface CNavigation {
    'primaryItems': any;
    'secondaryItems': any;
    'theme': string;
  }
  interface CNavigationAttributes extends StencilHTMLAttributes {
    'primaryItems'?: any;
    'secondaryItems'?: any;
    'theme'?: string;
  }

  interface RouterNavigation {
    'primaryItems': any;
  }
  interface RouterNavigationAttributes extends StencilHTMLAttributes {
    'primaryItems'?: any;
  }

  interface CRow {}
  interface CRowAttributes extends StencilHTMLAttributes {}

  interface CTheme {
    'name': string;
  }
  interface CThemeAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface UserRepos {
    'userId': string;
  }
  interface UserReposAttributes extends StencilHTMLAttributes {
    'userId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CCard': Components.CCard;
    'CCodeSample': Components.CCodeSample;
    'CColumn': Components.CColumn;
    'CContainer': Components.CContainer;
    'CContent': Components.CContent;
    'CField': Components.CField;
    'CFooter': Components.CFooter;
    'CHeader': Components.CHeader;
    'CHelloWorld': Components.CHelloWorld;
    'CIcon': Components.CIcon;
    'CList': Components.CList;
    'CNavigation': Components.CNavigation;
    'RouterNavigation': Components.RouterNavigation;
    'CRow': Components.CRow;
    'CTheme': Components.CTheme;
    'UserRepos': Components.UserRepos;
  }

  interface StencilIntrinsicElements {
    'c-card': Components.CCardAttributes;
    'c-code-sample': Components.CCodeSampleAttributes;
    'c-column': Components.CColumnAttributes;
    'c-container': Components.CContainerAttributes;
    'c-content': Components.CContentAttributes;
    'c-field': Components.CFieldAttributes;
    'c-footer': Components.CFooterAttributes;
    'c-header': Components.CHeaderAttributes;
    'c-hello-world': Components.CHelloWorldAttributes;
    'c-icon': Components.CIconAttributes;
    'c-list': Components.CListAttributes;
    'c-navigation': Components.CNavigationAttributes;
    'router-navigation': Components.RouterNavigationAttributes;
    'c-row': Components.CRowAttributes;
    'c-theme': Components.CThemeAttributes;
    'user-repos': Components.UserReposAttributes;
  }


  interface HTMLCCardElement extends Components.CCard, HTMLStencilElement {}
  var HTMLCCardElement: {
    prototype: HTMLCCardElement;
    new (): HTMLCCardElement;
  };

  interface HTMLCCodeSampleElement extends Components.CCodeSample, HTMLStencilElement {}
  var HTMLCCodeSampleElement: {
    prototype: HTMLCCodeSampleElement;
    new (): HTMLCCodeSampleElement;
  };

  interface HTMLCColumnElement extends Components.CColumn, HTMLStencilElement {}
  var HTMLCColumnElement: {
    prototype: HTMLCColumnElement;
    new (): HTMLCColumnElement;
  };

  interface HTMLCContainerElement extends Components.CContainer, HTMLStencilElement {}
  var HTMLCContainerElement: {
    prototype: HTMLCContainerElement;
    new (): HTMLCContainerElement;
  };

  interface HTMLCContentElement extends Components.CContent, HTMLStencilElement {}
  var HTMLCContentElement: {
    prototype: HTMLCContentElement;
    new (): HTMLCContentElement;
  };

  interface HTMLCFieldElement extends Components.CField, HTMLStencilElement {}
  var HTMLCFieldElement: {
    prototype: HTMLCFieldElement;
    new (): HTMLCFieldElement;
  };

  interface HTMLCFooterElement extends Components.CFooter, HTMLStencilElement {}
  var HTMLCFooterElement: {
    prototype: HTMLCFooterElement;
    new (): HTMLCFooterElement;
  };

  interface HTMLCHeaderElement extends Components.CHeader, HTMLStencilElement {}
  var HTMLCHeaderElement: {
    prototype: HTMLCHeaderElement;
    new (): HTMLCHeaderElement;
  };

  interface HTMLCHelloWorldElement extends Components.CHelloWorld, HTMLStencilElement {}
  var HTMLCHelloWorldElement: {
    prototype: HTMLCHelloWorldElement;
    new (): HTMLCHelloWorldElement;
  };

  interface HTMLCIconElement extends Components.CIcon, HTMLStencilElement {}
  var HTMLCIconElement: {
    prototype: HTMLCIconElement;
    new (): HTMLCIconElement;
  };

  interface HTMLCListElement extends Components.CList, HTMLStencilElement {}
  var HTMLCListElement: {
    prototype: HTMLCListElement;
    new (): HTMLCListElement;
  };

  interface HTMLCNavigationElement extends Components.CNavigation, HTMLStencilElement {}
  var HTMLCNavigationElement: {
    prototype: HTMLCNavigationElement;
    new (): HTMLCNavigationElement;
  };

  interface HTMLRouterNavigationElement extends Components.RouterNavigation, HTMLStencilElement {}
  var HTMLRouterNavigationElement: {
    prototype: HTMLRouterNavigationElement;
    new (): HTMLRouterNavigationElement;
  };

  interface HTMLCRowElement extends Components.CRow, HTMLStencilElement {}
  var HTMLCRowElement: {
    prototype: HTMLCRowElement;
    new (): HTMLCRowElement;
  };

  interface HTMLCThemeElement extends Components.CTheme, HTMLStencilElement {}
  var HTMLCThemeElement: {
    prototype: HTMLCThemeElement;
    new (): HTMLCThemeElement;
  };

  interface HTMLUserReposElement extends Components.UserRepos, HTMLStencilElement {}
  var HTMLUserReposElement: {
    prototype: HTMLUserReposElement;
    new (): HTMLUserReposElement;
  };

  interface HTMLElementTagNameMap {
    'c-card': HTMLCCardElement
    'c-code-sample': HTMLCCodeSampleElement
    'c-column': HTMLCColumnElement
    'c-container': HTMLCContainerElement
    'c-content': HTMLCContentElement
    'c-field': HTMLCFieldElement
    'c-footer': HTMLCFooterElement
    'c-header': HTMLCHeaderElement
    'c-hello-world': HTMLCHelloWorldElement
    'c-icon': HTMLCIconElement
    'c-list': HTMLCListElement
    'c-navigation': HTMLCNavigationElement
    'router-navigation': HTMLRouterNavigationElement
    'c-row': HTMLCRowElement
    'c-theme': HTMLCThemeElement
    'user-repos': HTMLUserReposElement
  }

  interface ElementTagNameMap {
    'c-card': HTMLCCardElement;
    'c-code-sample': HTMLCCodeSampleElement;
    'c-column': HTMLCColumnElement;
    'c-container': HTMLCContainerElement;
    'c-content': HTMLCContentElement;
    'c-field': HTMLCFieldElement;
    'c-footer': HTMLCFooterElement;
    'c-header': HTMLCHeaderElement;
    'c-hello-world': HTMLCHelloWorldElement;
    'c-icon': HTMLCIconElement;
    'c-list': HTMLCListElement;
    'c-navigation': HTMLCNavigationElement;
    'router-navigation': HTMLRouterNavigationElement;
    'c-row': HTMLCRowElement;
    'c-theme': HTMLCThemeElement;
    'user-repos': HTMLUserReposElement;
  }


}
